version: '3.8'
services:
  mongodb:
    container_name: smoothsick-mongodb
    image: mongo:6-jammy
    restart: always
    environment:
      MONGO_INITDB_DATABASE: smoothsick
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./migrations:/migrations
      - ../.mongo:/data/db
    command: mongod --auth --port 27017