name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i
        
      #- name: Linter
      #  run: npm run lint

      #- name: Types
      #  run: npm run check:types

      #- name: Tests
      #  run: npm run test:unit

      - name: Build
        run: npm run build
